version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      - GOOS: "linux"

    working_directory: /go/src/github.com/signalfx/tdigest

    steps:
      - checkout
      - run: 
          name: Setup Build Tools
          command: make install-build-tools
      - run:
          name: Go Lint
          command: make lint
      - run:
          name: Go Test
          command: make test

